export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const GET_LIST_VIDEOS = "GET_LIST_VIDEOS";
export const GET_LIST_VIDEOS_SUCCESS = "GET_LIST_VIDEOS_SUCCESS";
export const GET_LIST_VIDEOS_FAILURE = "GET_LIST_VIDEOS_FAILURE";
